// Article metadata only. Each post's body + FAQ live in src/posts/<id>.js and
// are loaded on demand (see loadPostBody in Blog.jsx). Keeping bodies here put
// all 28 articles (~150KB) into the chunk every reader downloads.
export const POSTS = [
  {
    id: "e-bolovanje-poslodavac",
    date: "27. avgust 2026",
    tag: "Bolovanje",
    title: "e-Bolovanje za poslodavce 2026: 6 koraka",
    summary: "Registracija na eUpravi do 1.1.2026, elektronski zahtevi RFZO-u od 1.4.2026, novi pravilnik od 8.8.2026. Koraci, rokovi 15-21-7 i kazne do 200.000 RSD.",
    ogImage: "https://www.platnilistic.rs/media/blog/e-bolovanje-poslodavac.png",
    hasFaq: true,
  },
  {
    id: "e-bolovanje-zaposleni",
    date: "27. avgust 2026",
    tag: "Bolovanje",
    title: "E-bolovanje za zaposlene: šta morate sami",
    summary: "Doznaku više ne nosite poslodavcu: član 103. Zakona o radu je ukinut. Šta zaposleni mora sam da uradi, rok od tri dana kod lekara i kada stiže naknada.",
    ogImage: "https://www.platnilistic.rs/media/blog/e-bolovanje-zaposleni.png",
    hasFaq: true,
  },
  {
    id: "kupovna-moc-plate-2016-2026",
    date: "4. avgust 2026",
    updated: "27. avgust 2026",
    tag: "Data studija",
    title: "Kupovna moć plate u Srbiji 2016–2026: realno +53%",
    summary: "Plata iz 2016. vredela je koliko danas vredi 71.558 din — a prosečna je danas 109.462. Realan rast kupovne moći je 53%, uz jedini pad 2022. Ko je zaista najviše dobio (RZS podaci).",
    ogImage: "https://www.platnilistic.rs/media/kupovna-moc-2016-2026.png",
    hasFaq: true,
  },
  {
    id: "sporazumni-raskid",
    date: "4. avgust 2026",
    tag: "Zakon o radu",
    title: "Sporazumni raskid ugovora o radu 2026 — šta gubite potpisom",
    summary: "Sporazumni raskid: pisani sporazum, nema otkaznog roka, ali po pravilu gubite pravo na NSZ naknadu dok ne navršite 12 meseci osiguranja. Šta sporazum mora da sadrži.",
    hasFaq: true,
  },
  {
    id: "probni-rad",
    date: "4. avgust 2026",
    tag: "Zakon o radu",
    title: "Probni rad 2026 — najduže 6 meseci, otkazni rok 5 dana",
    summary: "Probni rad traje najduže 6 meseci (čl. 36), otkazni rok je najmanje 5 radnih dana za obe strane, a poslodavac mora obrazložiti otkaz. Prava i najčešće greške.",
    hasFaq: true,
  },
  {
    id: "mobing",
    date: "4. avgust 2026",
    tag: "Zakon o radu",
    title: "Mobing na radnom mestu 2026 — kako da prijavite zlostavljanje",
    summary: "Mobing: pisani zahtev poslodavcu u roku od 6 meseci, posredovanje za 8–30 dana, tužba u roku od 15 dana ako ne uspe. Definicija, postupak i teret dokazivanja.",
    hasFaq: true,
  },
  {
    id: "neplaceno-odsustvo",
    date: "4. avgust 2026",
    tag: "Zakon o radu",
    title: "Neplaćeno odsustvo 2026 — trajanje, staž i zdravstveno",
    summary: "Neplaćeno odsustvo: zakon ne propisuje maksimalno trajanje, staž osiguranja ne teče, a status zdravstvenog treba proveriti kod RFZO. Prava i postupak zahteva.",
    hasFaq: true,
  },
  {
    id: "nezakonit-otkaz",
    date: "4. avgust 2026",
    tag: "Zakon o radu",
    title: "Nezakonit otkaz 2026 — rok za tužbu 60 dana, naknada do 18 zarada",
    summary: "Nezakonit otkaz: tužba u roku od 60 dana, sud može naložiti vraćanje na rad ili naknadu do 18 zarada (36 ako je povratak nemoguć). Koraci i najčešći razlozi.",
    hasFaq: true,
  },
  {
    id: "disciplinski-postupak",
    date: "4. avgust 2026",
    tag: "Zakon o radu",
    title: "Disciplinski postupak 2026 — upozorenje, rok i blaže mere",
    summary: "Disciplinski postupak: obavezno pisano upozorenje sa 8 dana za odgovor, rok 6 meseci/1 godina za pokretanje, i blaže mere umesto otkaza (čl. 179a). Vodič.",
    hasFaq: true,
  },
  {
    id: "otkazni-rok",
    date: "16. jul 2026",
    updated: "6. avgust 2026",
    tag: "Zakon o radu",
    title: "Otkazni rok 2026 — 15, 8–30 ili 5 dana: svi slučajevi",
    summary: "Otkazni rok: 15 dana kad zaposleni da otkaz (max 30), 8–30 dana kod otkaza zbog rezultata rada, 5 radnih dana na probnom radu. Od kog dana teče + primer.",
    hasFaq: true,
  },
  {
    id: "pdv-prag-preduzetnik",
    date: "13. jul 2026",
    updated: "6. avgust 2026",
    tag: "Porez",
    title: "PDV za preduzetnike 2026 — prag 8 miliona i kada u sistem",
    summary: "PDV prag je 8.000.000 RSD u prethodnih 12 meseci, ne po kalendarskoj godini. Rok za EPPDV, stope 20% i 10%, ino usluge i dobrovoljni ulazak (min. 2 godine).",
    hasFaq: true,
  },
  {
    id: "registracija-doo",
    date: "13. jul 2026",
    updated: "6. avgust 2026",
    tag: "Biznis",
    title: "Registracija DOO u Srbiji 2026 — koraci, rokovi i troškovi",
    summary: "Registracija DOO 2026: e-prijava u APR ≈5.900 RSD, osnivački akt i notar, rešenje za 3–5 radnih dana, kapital 100 RSD i obaveze u prvih 15 dana (PDP, CEV).",
    hasFaq: true,
  },
  {
    id: "sifre-delatnosti-pausal",
    date: "13. jul 2026",
    updated: "6. avgust 2026",
    tag: "Paušal",
    title: "Šifre delatnosti za paušalce 2026 — koje mogu, a koje ne",
    summary: "Šifre delatnosti za paušalce 2026: koje ne mogu u paušal, koeficijenti po šiframa (6201 → 4,025), 15 šifri sa republičkom osnovicom i zamka promene šifre.",
    hasFaq: true,
  },
  {
    id: "limit-za-pausalce",
    date: "13. jul 2026",
    updated: "6. avgust 2026",
    tag: "Paušal",
    title: "Limit za paušalce 2026 — 6 i 8 miliona: šta kad se pređe",
    summary: "Limit za paušalce: 6.000.000 RSD u kalendarskoj godini, PDV prag 8.000.000 u 365 dana. Kada knjige kreću od 1. jula, a kada od 1. januara — vodič sa rokovima.",
    hasFaq: true,
  },
  {
    id: "godisnji-porez-na-dohodak",
    date: "13. jul 2026",
    updated: "6. avgust 2026",
    tag: "Porez",
    title: "Godišnji porez na dohodak građana 2026 — ko plaća i koliko",
    summary: "Godišnji porez na dohodak građana: cenzus za 2025. je 5.439.096 RSD, stope 10% i 15%, prijava PP GPDG do 15. maja. Obračun, olakšica do 40 godina i primeri.",
    hasFaq: true,
  },
  {
    id: "porodiljsko-odsustvo",
    date: "11. jul 2026",
    updated: "27. avgust 2026",
    tag: "Zakon o radu",
    title: "Porodiljsko odsustvo 2026 — naknada, obračun i isplata",
    summary: "Isplata porodiljskog stiže po pravilu oko 20. u mesecu — zakon ne fiksira datum. Naknada = prosek osnovica za 18 meseci, najviše 5 prosečnih zarada.",
    hasFaq: true,
  },
  {
    id: "otkaz-ugovora-o-radu",
    date: "25. jun 2026",
    updated: "27. avgust 2026",
    tag: "Zakon o radu",
    title: "Otkaz ugovora o radu 2026 — razlozi, postupak i otpremnina",
    summary: "Otkaz ugovora o radu 2026: razlozi za otkaz po Zakonu o radu, otkazni rok (8–30 dana), otpremnina za tehnološki višak i prava zaposlenog. Obračun sa primerom.",
    hasFaq: true,
  },
  {
    id: "prosecna-plata-srbija",
    date: "19. jun 2026",
    updated: "27. avgust 2026",
    tag: "Zarada",
    title: "Prosečna plata u Srbiji 2026: 120.401 din (1.026 €), jun",
    summary: "120.401 din (≈1.026 €) — prosečna neto plata u Srbiji, jun 2026 (RZS). Bruto 166.123, medijalna 94.281 din. Pregled po mesecima, sektorima i gradovima.",
    ogImage: "https://www.platnilistic.rs/media/prosecna-plata-2026.png",
    hasFaq: true,
  },
  {
    id: "kako-registrovati-firmu",
    date: "17. jun 2026",
    updated: "6. avgust 2026",
    tag: "Biznis",
    title: "Kako registrovati firmu u Srbiji 2026 — paušal ili DOO",
    summary: "Kako registrovati firmu u Srbiji 2026: paušal, preduzetnik ili DOO — koraci u APR-u, troškovi, porezi i koju formu izabrati. Vodič korak po korak.",
    hasFaq: true,
  },
  {
    id: "pausal-ili-doo",
    date: "17. jun 2026",
    updated: "6. avgust 2026",
    tag: "Biznis",
    title: "Paušal ili DOO 2026 — poređenje i šta se više isplati",
    summary: "Paušal ili DOO 2026: paušalac plaća fiksno ≈30–45.000 RSD/mes, kod DOO na izvučenu dobit ode ~27,75%. Tabela poređenja, odgovornost i kada se šta isplati.",
    hasFaq: true,
  },
  {
    id: "koliko-pausalac-placa-mesecno",
    date: "17. jun 2026",
    updated: "6. avgust 2026",
    tag: "Paušal",
    title: "Koliko paušalac plaća mesečno 2026? Okvirno 30–45.000 RSD",
    summary: "Koliko paušalac plaća mesečno u 2026: okvirno 30.000–45.000 RSD, zavisno od šifre delatnosti i opštine. Šta čine porez i doprinosi (45,05%) i gde je tačna cifra.",
    hasFaq: true,
  },
  {
    id: "registracija-pausalca",
    date: "17. jun 2026",
    updated: "6. avgust 2026",
    tag: "Biznis",
    title: "Kako registrovati paušalca korak po korak (APR) 2026",
    summary: "Kako registrovati paušalca u Srbiji 2026: izbor šifre delatnosti, e-registracija u APR-u za ≈2.500 RSD, zahtev za paušal i prve obaveze — korak po korak.",
    hasFaq: true,
  },
  {
    id: "uplate-iz-inostranstva",
    date: "17. jun 2026",
    updated: "6. avgust 2026",
    tag: "Frilenseri",
    title: "Uplate iz inostranstva 2026 — Wise, Payoneer ili devizni račun",
    summary: "Kako primati uplate iz inostranstva u Srbiji 2026: Wise, Payoneer i devizni račun — naknade, kurs i prijava poreza. I zašto Revolut još ne radi za rezidente.",
    hasFaq: true,
  },
  {
    id: "kosta-otvaranje-firme",
    date: "17. jun 2026",
    updated: "6. avgust 2026",
    tag: "Biznis",
    title: "Koliko košta otvaranje firme 2026? Paušal od 2.500 RSD",
    summary: "Koliko košta otvaranje firme u Srbiji 2026: APR naknada za paušal ≈2.500–2.900 RSD, DOO ≈5.900 RSD online. Notar, minimalni kapital 100 RSD i realan ukupan trošak.",
    hasFaq: true,
  },
  {
    id: "frilenser-pausalac-firma",
    date: "17. jun 2026",
    updated: "6. avgust 2026",
    tag: "Frilenseri",
    title: "Frilenser, paušalac ili firma — kada preći na radnju?",
    summary: "Kada se frilenseru isplati prelazak na paušal ili otvaranje firme? Poredimo poreze, troškove, fakturisanje i odgovornost — i kada je pravi trenutak.",
    hasFaq: true,
  },
  {
    id: "ugovor-o-delu",
    date: "14. jun 2026",
    updated: "6. avgust 2026",
    tag: "Ugovori",
    title: "Ugovor o delu 2026 — porez, doprinosi i obračun (sa primerom)",
    summary: "Ugovor o delu u Srbiji 2026: porez 20%, PIO 24% i zdravstvo 10,3%, normirani troškovi 20% i primer obračuna bruto u neto — koliko zaista ostaje na ruke.",
    hasFaq: true,
  },
  {
    id: "topli-obrok-i-regres",
    date: "11. jun 2026",
    updated: "6. avgust 2026",
    tag: "Zarada",
    title: "Topli obrok i regres 2026: da li su obavezni i ko ima pravo",
    summary: "Da, topli obrok i regres su obavezan deo zarade po Zakonu o radu — ali zakon ne propisuje iznos, već ga određuje poslodavac. Ne ulaze u minimalac i oporezuju se kao zarada.",
    hasFaq: true,
  },
  {
    id: "pausalno-oporezivanje",
    date: "8. jun 2026",
    updated: "6. avgust 2026",
    tag: "Paušal",
    title: "Paušalno oporezivanje 2026 — ko može i koliko plaća?",
    summary: "Paušalno oporezivanje 2026: limit 6 miliona RSD, mesečno okvirno 30–45.000 RSD (porez + doprinosi), koje delatnosti ne mogu u paušal. Vodič za preduzetnike.",
    hasFaq: true,
  },
  {
    id: "porez-za-frilensere",
    date: "5. jun 2026",
    updated: "6. avgust 2026",
    tag: "Frilenseri",
    title: "Porez za frilensere 2026 — Model A ili B (šta se isplati)",
    summary: "Frilenseri u Srbiji 2026 sami plaćaju porez kvartalno, biranjem Modela A ili B. Objašnjavamo normirane troškove, stope, doprinose, rokove i primer obračuna.",
    hasFaq: true,
  },
  {
    id: "kako-se-obracunava-penzija",
    date: "12. maj 2026",
    updated: "6. avgust 2026",
    tag: "Penzija",
    title: "Kako se obračunava penzija u Srbiji — formula i primeri",
    summary: "Kako se obračunava penzija u Srbiji 2026: bodovni sistem, lični bodovi i koeficijent, uslovi za starosnu, prevremenu i invalidsku penziju — uz primere.",
    hasFaq: false,
  },
  {
    id: "kako-se-obracunava-bolovanje",
    date: "1. maj 2026",
    updated: "27. avgust 2026",
    tag: "Bolovanje",
    title: "Kako se obračunava bolovanje do 30 dana — naknada 65%",
    summary: "Obračun bolovanja do 30 dana: naknada je minimum 65% prosečne zarade, a od 31. dana na teret RFZO. Kalkulator sa primerima i PDF platni listić.",
    hasFaq: false,
  },
  {
    id: "minuli-rad-obracun",
    date: "15. april 2026",
    updated: "6. avgust 2026",
    tag: "Zakon o radu",
    title: "Minuli rad — kako se obračunava i koliko iznosi po godini staža?",
    summary: "Minuli rad je obavezno uvećanje zarade od 0,4% za svaku godinu rada kod istog poslodavca. Detaljan vodič sa primerima obračuna prema članu 108. Zakona o radu.",
    hasFaq: true,
  },
  {
    id: "porez-na-bonus",
    date: "1. mart 2026",
    updated: "6. avgust 2026",
    tag: "Porez",
    title: "Porez na bonus i nagradu zaposlenima — koliko se zaista oporezuje?",
    summary: "Bonus, godišnja nagrada, 13. plata i jubilarna nagrada — sve što treba znati o porezima i doprinosima na nestandardna primanja zaposlenih u Srbiji.",
    hasFaq: false,
  },
  {
    id: "jubilarna-nagrada",
    date: "15. februar 2026",
    updated: "27. avgust 2026",
    tag: "Porez",
    title: "Jubilarna nagrada 2026 — iznos, porez i neoporezivih 28.912",
    summary: "Jubilarna nagrada 2026: visina je stvar kolektivnog ugovora (obično 1–3 prosečne zarade), neoporezivo je 28.912 RSD godišnje, a iznad se plaća samo porez 10% — bez doprinosa.",
    hasFaq: true,
  },
  {
    id: "neoporezivi-2026",
    date: "1. februar 2026",
    updated: "6. avgust 2026",
    tag: "Porez",
    title: "Neoporezivi iznos zarade u 2026. godini: 34.221 RSD",
    summary: "Od 1. januara 2026. godine, neoporezivi iznos zarade iznosi 34.221 RSD mesečno. Šta to znači za obračun poreza na zaradu i koliko štedite?",
    hasFaq: false,
  },
  {
    id: "bruto-neto-razlika",
    date: "15. januar 2025",
    updated: "6. avgust 2026",
    tag: "Osnove",
    title: "Razlika bruto i neto zarade 2026 — od 100.000 ostaje 73.522",
    summary: "Razlika između bruto i neto zarade 2026: od bruto 1 se odbija 19,90% doprinosa + 10% poreza, pa od 100.000 RSD bruto ostaje ≈73.522 neto. Primeri i formula.",
    hasFaq: false,
  },
  {
    id: "prekovremeni-rad",
    date: "10. januar 2025",
    updated: "6. avgust 2026",
    tag: "Zakon o radu",
    title: "Prekovremeni rad 2026 — najmanje +26% po satu (čl. 108)",
    summary: "Prekovremeni rad se plaća najmanje +26% na satnicu, rad na praznik +110% (čl. 108 Zakona o radu). Limit: 8 h nedeljno. Obračun sa primerom za 2026.",
    hasFaq: true,
  },
  {
    id: "minimalna-zarada-2025",
    date: "2. januar 2025",
    tag: "Novosti",
    title: "Minimalna zarada 2025: 73.274 RSD bruto (arhiva)",
    summary: "Arhiva: minimalna zarada za 2025. godinu iznosila je 73.274 RSD bruto. Za aktuelne iznose pogledajte minimalnu zaradu za 2026.",
    hasFaq: false,
  },
  {
    id: "doprinosi-srbija",
    date: "20. decembar 2024",
    updated: "6. avgust 2026",
    tag: "Doprinosi",
    title: "Doprinosi za socijalno osiguranje u Srbiji (vodič)",
    summary: "Ko plaća doprinose, koliko iznose i na šta imate pravo? Kompletan pregled sistema socijalnog osiguranja za zaposlene u Srbiji.",
    hasFaq: false,
  },
  {
    id: "minimalna-zarada-2026",
    date: "1. februar 2026",
    updated: "6. avgust 2026",
    tag: "Novosti",
    title: "Minimalna zarada u Srbiji za 2026. godinu",
    summary: "Minimalna cena rada za 2026. iznosi 371 RSD neto po radnom času (od 1. januara), tj. mesečno oko 59.360–68.264 RSD neto. Šta se promenilo i kako utiče na poslodavce?",
    hasFaq: false,
  },
  {
    id: "godisnji-odmor-naknada",
    date: "15. januar 2026",
    updated: "6. avgust 2026",
    tag: "Zakon o radu",
    title: "Kako se računa naknada za godišnji odmor 2026",
    summary: "Kako se računa i plaća godišnji odmor po Zakonu o radu? Naknada ne može biti niža od proseka zarade u prethodnih 12 meseci — formula, primer i prava.",
    hasFaq: true,
  },
  {
    id: "otpremnina-obracun",
    date: "5. januar 2026",
    updated: "27. avgust 2026",
    tag: "Zakon o radu",
    title: "Otpremnina za penziju i tehnološki višak — iznos, obračun i porez",
    summary: "Otpremnina za odlazak u penziju: najmanje 2 prosečne zarade RS (240.802 RSD, jun 2026). Za tehnološki višak: min. 1/3 zarade po godini staža. Obračun i porez.",
    hasFaq: true,
  },
];
// Old blog slugs that have been consolidated into a canonical page. Single
// source of truth for BOTH the client-side redirect (Blog.jsx / BlogPostRoute)
// and the exclusion from user-facing listings. Keep in sync with the
// platform-level 301s in vercel.json — these must map to the same destinations.
// The client-side redirect matters because the SPA router (React Router) can
// render /blog/:slug before the Vercel redirect ever fires (client navigation
// and the index.html rewrite both hand control to the app); without it, the
// old URL keeps serving a full article and Google never consolidates rankings.
export const REDIRECT_MAP = {
  "bruto-neto-razlika": "/",
  "neoporezivi-2025": "/neoporezivi-iznos-2026",
  "neoporezivi-2026": "/neoporezivi-iznos-2026",
  "minimalna-zarada-2026": "/minimalna-zarada",
  "minimalna-zarada-2025": "/minimalna-zarada",
};
export const REDIRECTED_POST_IDS = new Set(Object.keys(REDIRECT_MAP));

// POSTS minus redirected ones — use this for any user-facing listing.
export const LIVE_POSTS = POSTS.filter((p) => !REDIRECTED_POST_IDS.has(p.id));