// Article metadata only. Each post's body + FAQ live in src/posts/<id>.js and
// are loaded on demand (see loadPostBody in Blog.jsx). Keeping bodies here put
// all 28 articles (~150KB) into the chunk every reader downloads.
export const POSTS = [
  {
    id: "limit-za-pausalce",
    date: "13. jul 2026",
    tag: "Paušal",
    title: "Limit za paušalce 2026 — 6 i 8 miliona: šta kad se pređe",
    summary: "Limit za paušalce: 6.000.000 RSD u kalendarskoj godini, PDV prag 8.000.000 u 365 dana. Kada knjige kreću od 1. jula, a kada od 1. januara — vodič sa rokovima.",
    hasFaq: true,
  },
  {
    id: "godisnji-porez-na-dohodak",
    date: "13. jul 2026",
    tag: "Porez",
    title: "Godišnji porez na dohodak građana 2026 — ko plaća i koliko",
    summary: "Godišnji porez na dohodak građana: cenzus za 2025. je 5.439.096 RSD, stope 10% i 15%, prijava PP GPDG do 15. maja. Obračun, olakšica do 40 godina i primeri.",
    hasFaq: true,
  },
  {
    id: "porodiljsko-odsustvo",
    date: "11. jul 2026",
    tag: "Zakon o radu",
    title: "Porodiljsko odsustvo 2026 — naknada, obračun i isplata",
    summary: "Porodiljsko odsustvo 2026: naknada je prosek osnovica za 18 meseci, najviše 5 prosečnih zarada, tokom prva 3 meseca najmanje minimalac. Obračun sa primerima.",
    hasFaq: true,
  },
  {
    id: "otkaz-ugovora-o-radu",
    date: "25. jun 2026",
    updated: "13. jul 2026",
    tag: "Zakon o radu",
    title: "Otkaz ugovora o radu 2026 — otkazni rok, otpremnina i prava",
    summary: "Otkaz ugovora o radu 2026: razlozi za otkaz po Zakonu o radu, otkazni rok (8–30 dana), otpremnina za tehnološki višak i prava zaposlenog. Obračun sa primerom.",
    hasFaq: true,
  },
  {
    id: "prosecna-plata-srbija",
    date: "19. jun 2026",
    updated: "8. jul 2026",
    tag: "Zarada",
    title: "Prosečna plata u Srbiji 2026: 121.805 din (1.038 €), april",
    summary: "Prosečna neto plata u Srbiji za april 2026. je 121.805 din (≈1.038 €), bruto 168.008, medijalna 94.585 (RZS). Pregled po mesecima, sektorima i gradovima.",
    ogImage: "https://www.platnilistic.rs/media/prosecna-plata-2026.png",
    hasFaq: true,
  },
  {
    id: "kako-registrovati-firmu",
    date: "17. jun 2026",
    tag: "Biznis",
    title: "Kako registrovati firmu u Srbiji 2026 — paušal ili DOO",
    summary: "Kako registrovati firmu u Srbiji 2026: paušal, preduzetnik ili DOO — koraci u APR-u, troškovi, porezi i koju formu izabrati. Vodič korak po korak.",
    hasFaq: true,
  },
  {
    id: "pausal-ili-doo",
    date: "17. jun 2026",
    updated: "13. jul 2026",
    tag: "Biznis",
    title: "Paušal ili DOO 2026 — poređenje i šta se više isplati",
    summary: "Paušal ili DOO 2026: paušalac plaća fiksno ≈30–45.000 RSD/mes, kod DOO na izvučenu dobit ode ~27,75%. Tabela poređenja, odgovornost i kada se šta isplati.",
    hasFaq: true,
  },
  {
    id: "koliko-pausalac-placa-mesecno",
    date: "17. jun 2026",
    updated: "13. jul 2026",
    tag: "Paušal",
    title: "Koliko paušalac plaća mesečno 2026? Okvirno 30–45.000 RSD",
    summary: "Koliko paušalac plaća mesečno u 2026: okvirno 30.000–45.000 RSD, zavisno od šifre delatnosti i opštine. Šta čine porez i doprinosi (45,05%) i gde je tačna cifra.",
    hasFaq: true,
  },
  {
    id: "registracija-pausalca",
    date: "17. jun 2026",
    updated: "13. jul 2026",
    tag: "Biznis",
    title: "Kako registrovati paušalca korak po korak (APR) 2026",
    summary: "Kako registrovati paušalca u Srbiji 2026: izbor šifre delatnosti, e-registracija u APR-u za ≈2.500 RSD, zahtev za paušal i prve obaveze — korak po korak.",
    hasFaq: true,
  },
  {
    id: "uplate-iz-inostranstva",
    date: "17. jun 2026",
    tag: "Frilenseri",
    title: "Uplate iz inostranstva 2026 — Wise, Payoneer ili devizni račun",
    summary: "Kako primati uplate iz inostranstva u Srbiji 2026: Wise, Payoneer i devizni račun — naknade, kurs i prijava poreza. I zašto Revolut još ne radi za rezidente.",
    hasFaq: true,
  },
  {
    id: "kosta-otvaranje-firme",
    date: "17. jun 2026",
    updated: "13. jul 2026",
    tag: "Biznis",
    title: "Koliko košta otvaranje firme 2026? Paušal od 2.500 RSD",
    summary: "Koliko košta otvaranje firme u Srbiji 2026: APR naknada za paušal ≈2.500–2.900 RSD, DOO ≈5.900 RSD online. Notar, minimalni kapital 100 RSD i realan ukupan trošak.",
    hasFaq: true,
  },
  {
    id: "frilenser-pausalac-firma",
    date: "17. jun 2026",
    tag: "Frilenseri",
    title: "Frilenser, paušalac ili firma — kada preći na radnju?",
    summary: "Kada se frilenseru isplati prelazak na paušal ili otvaranje firme? Poredimo poreze, troškove, fakturisanje i odgovornost — i kada je pravi trenutak.",
    hasFaq: true,
  },
  {
    id: "ugovor-o-delu",
    date: "14. jun 2026",
    tag: "Ugovori",
    title: "Ugovor o delu 2026 — porez, doprinosi i obračun (sa primerom)",
    summary: "Ugovor o delu u Srbiji 2026: porez 20%, PIO 24% i zdravstvo 10,3%, normirani troškovi 20% i primer obračuna bruto u neto — koliko zaista ostaje na ruke.",
    hasFaq: true,
  },
  {
    id: "topli-obrok-i-regres",
    date: "11. jun 2026",
    updated: "8. jul 2026",
    tag: "Zarada",
    title: "Topli obrok i regres 2026: da li su obavezni i ko ima pravo",
    summary: "Da, topli obrok i regres su obavezan deo zarade po Zakonu o radu — ali zakon ne propisuje iznos, već ga određuje poslodavac. Ne ulaze u minimalac i oporezuju se kao zarada.",
    hasFaq: true,
  },
  {
    id: "pausalno-oporezivanje",
    date: "8. jun 2026",
    updated: "13. jul 2026",
    tag: "Paušal",
    title: "Paušalno oporezivanje 2026 — ko može i koliko plaća?",
    summary: "Paušalno oporezivanje 2026: limit 6 miliona RSD, mesečno okvirno 30–45.000 RSD (porez + doprinosi), koje delatnosti ne mogu u paušal. Vodič za preduzetnike.",
    hasFaq: true,
  },
  {
    id: "porez-za-frilensere",
    date: "5. jun 2026",
    tag: "Frilenseri",
    title: "Porez za frilensere 2026 — Model A ili B (šta se isplati)",
    summary: "Frilenseri u Srbiji 2026 sami plaćaju porez kvartalno, biranjem Modela A ili B. Objašnjavamo normirane troškove, stope, doprinose, rokove i primer obračuna.",
    hasFaq: true,
  },
  {
    id: "kako-se-obracunava-penzija",
    date: "12. maj 2026",
    tag: "Penzija",
    title: "Kako se obračunava penzija u Srbiji — formula i primeri",
    summary: "Kako se obračunava penzija u Srbiji 2026: bodovni sistem, lični bodovi i koeficijent, uslovi za starosnu, prevremenu i invalidsku penziju — uz primere.",
    hasFaq: false,
  },
  {
    id: "kako-se-obracunava-bolovanje",
    date: "1. maj 2026",
    tag: "Bolovanje",
    title: "Kako se obračunava bolovanje do 30 dana — naknada 65%",
    summary: "Obračun bolovanja do 30 dana: naknada je minimum 65% prosečne zarade, a od 31. dana na teret RFZO. Kalkulator sa primerima i PDF platni listić.",
    hasFaq: false,
  },
  {
    id: "minuli-rad-obracun",
    date: "15. april 2026",
    tag: "Zakon o radu",
    title: "Minuli rad — kako se obračunava i koliko iznosi po godini staža?",
    summary: "Minuli rad je obavezno uvećanje zarade od 0,4% za svaku godinu rada kod istog poslodavca. Detaljan vodič sa primerima obračuna prema članu 108. Zakona o radu.",
    hasFaq: true,
  },
  {
    id: "porez-na-bonus",
    date: "1. mart 2026",
    updated: "13. jul 2026",
    tag: "Porez",
    title: "Porez na bonus i nagradu zaposlenima — koliko se zaista oporezuje?",
    summary: "Bonus, godišnja nagrada, 13. plata i jubilarna nagrada — sve što treba znati o porezima i doprinosima na nestandardna primanja zaposlenih u Srbiji.",
    hasFaq: false,
  },
  {
    id: "jubilarna-nagrada",
    date: "15. februar 2026",
    updated: "13. jul 2026",
    tag: "Porez",
    title: "Jubilarna nagrada 2026 — iznos, porez i neoporezivih 28.912",
    summary: "Jubilarna nagrada 2026: visina je stvar kolektivnog ugovora (obično 1–3 prosečne zarade), neoporezivo je 28.912 RSD godišnje, a iznad se plaća samo porez 10% — bez doprinosa.",
    hasFaq: true,
  },
  {
    id: "neoporezivi-2026",
    date: "1. februar 2026",
    tag: "Porez",
    title: "Neoporezivi iznos zarade u 2026. godini: 34.221 RSD",
    summary: "Od 1. januara 2026. godine, neoporezivi iznos zarade iznosi 34.221 RSD mesečno. Šta to znači za obračun poreza na zaradu i koliko štedite?",
    hasFaq: false,
  },
  {
    id: "bruto-neto-razlika",
    date: "15. januar 2025",
    updated: "8. jul 2026",
    tag: "Osnove",
    title: "Razlika između bruto i neto zarade — jednostavno objašnjenje",
    summary: "Bruto zarada i neto zarada — dva pojma koja svaki zaposleni čuje, ali malo ko zapravo razume šta ih razlikuje. Evo jasnog objašnjenja za 2026.",
    hasFaq: false,
  },
  {
    id: "prekovremeni-rad",
    date: "10. januar 2025",
    updated: "8. jul 2026",
    tag: "Zakon o radu",
    title: "Prekovremeni rad u Srbiji: prava i obračun po Zakonu o radu",
    summary: "Zakon o radu propisuje minimum od +26% za prekovremeni rad. Kako se obračunava, koliko može trajati i šta su vaša prava kao zaposlenog?",
    hasFaq: true,
  },
  {
    id: "minimalna-zarada-2025",
    date: "2. januar 2025",
    tag: "Novosti",
    title: "Minimalna zarada 2025: 73.274 RSD bruto (arhiva)",
    summary: "Arhiva: minimalna zarada za 2025. godinu iznosila je 73.274 RSD bruto. Za aktuelne iznose pogledajte minimalnu zaradu za 2026.",
    hasFaq: false,
  },
  {
    id: "doprinosi-srbija",
    date: "20. decembar 2024",
    tag: "Doprinosi",
    title: "Doprinosi za socijalno osiguranje u Srbiji (vodič)",
    summary: "Ko plaća doprinose, koliko iznose i na šta imate pravo? Kompletan pregled sistema socijalnog osiguranja za zaposlene u Srbiji.",
    hasFaq: false,
  },
  {
    id: "minimalna-zarada-2026",
    date: "1. februar 2026",
    tag: "Novosti",
    title: "Minimalna zarada u Srbiji za 2026. godinu",
    summary: "Minimalna cena rada za 2026. iznosi 371 RSD neto po radnom času (od 1. januara), tj. mesečno oko 59.360–68.264 RSD neto. Šta se promenilo i kako utiče na poslodavce?",
    hasFaq: false,
  },
  {
    id: "godisnji-odmor-naknada",
    date: "15. januar 2026",
    updated: "13. jul 2026",
    tag: "Zakon o radu",
    title: "Kako se računa naknada za godišnji odmor 2026",
    summary: "Kako se računa i plaća godišnji odmor po Zakonu o radu? Naknada ne može biti niža od proseka zarade u prethodnih 12 meseci — formula, primer i prava.",
    hasFaq: true,
  },
  {
    id: "otpremnina-obracun",
    date: "5. januar 2026",
    updated: "13. jul 2026",
    tag: "Zakon o radu",
    title: "Otpremnina u Srbiji — minimalni iznos, obračun i porez",
    summary: "Otpremnina u Srbiji: ko ima pravo, kolika je minimalna otpremnina po Zakonu o radu i kako se plaća porez na otpremninu. Obračun za tehnološki višak i odlazak u penziju.",
    hasFaq: true,
  },
];
export const REDIRECTED_POST_IDS = new Set(["neoporezivi-2026", "minimalna-zarada-2026"]);

// POSTS minus redirected ones — use this for any user-facing listing.
export const LIVE_POSTS = POSTS.filter((p) => !REDIRECTED_POST_IDS.has(p.id));